- name: install psycopg2
  become: true
  apt: name=python-psycopg2 state=present

- name: install postgresql server
  become: true
  apt: name=postgresql state=present

- name: install postgresql client
  become: true
  apt: name=postgresql-client state=present

- name: create vagrant user
  become: true
  become_user: postgres
  postgresql_user: name=vagrant role_attr_flags=SUPERUSER

- name: create vagrant database
  become: true
  become_user: postgres
  postgresql_db: name=vagrant owner=vagrant
