- name: remove default vhost
  become: true
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: create vhost
  become: true
  copy: src=vhost dest=/etc/nginx/sites-available/

- name: create site
  copy: src=index.php dest=~/public_html/test

- name: enable vhost
  become: true
  file: src=/etc/nginx/sites-available/php-test dest=/etc/nginx/sites-enabled/php-test state=link

- name: reload nginx
  become: true
  service: name=nginx state=reloaded
