- name: maildir for opensmtpd (1)
  become: true
  lineinfile: dest=/etc/smtpd.conf
    regexp='^accept from any for domain "example.org" alias <aliases> deliver to '
    line='accept from any for domain "example.org" alias <aliases> deliver to maildir'

- name: maildir for opensmtpd (2)
  become: true
  lineinfile: dest=/etc/smtpd.conf
    regexp='^accept for local alias <aliases> deliver to '
    line='accept for local alias <aliases> deliver to maildir'

- name: reload opensmtpd service
  become: true
  service: name=opensmtpd state=restarted

- name: maildir for dovecot
  become: true
  lineinfile: dest=/etc/dovecot/conf.d/99-custom.conf
    line='mail_location = maildir:~/Maildir'

- name: reload dovecot service
  become: true
  service: name=dovecot state=restarted
